### ISSUE TITLE
Add graphql-ws v6 to peer deps

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/app-extension-apollo#173]
The breaking changes made in v6 are only related to server usage:
https://github.com/enisdenjo/graphql-ws/releases/tag/v6.0.0
So, the client usage in this AE is not affected and will still work as before.

This range can be updated to include `^6.0.0`:
https://github.com/quasarframework/app-extension-apollo/blob/6e0795211cb9c5e44ed6d1e171d1607895553dc0/package.json#L57

**Comment by smolinari** [comment]
Fixed via https://github.com/quasarframework/app-extension-apollo/pull/175

Scott

**Comment by yusufkandemir** [comment]
Thanks, but I said it can be included, but it should not be the only thing. `"graphql-ws": "^5.14.0 || ^6.0.0",` should allow both 5 and 6. The existing users will start getting warnings/errors now and forced to upgrade to v6. The upgrade is nothing special, but it's still not great IMO.
